MY.WantGlideinDevel = true
requirements = TARGET.IsGlideinDevel_Site

executable = /usr/bin/sleep
transfer_executable = false
arguments = 7200

request_cpus = 1
request_memory = 1MB
request_disk = 1MB

error = logs/sleep.$(Cluster).$(Process).err
output = logs/sleep.$(Cluster).$(Process).out
log = logs/sleep.$(Cluster).log

on_exit_remove = false
cron_minute = 0
cron_hour = */3
cron_day_of_month = *
cron_month = *
cron_day_of_week = *

+FacilitatorOverride = True

queue 50
